### ISSUE TITLE
AttributeError: 'LegacyEnvConfigHandler' object has no attribute 'env_dir_name'

### ISSUE THREAD

**Issue by psegedy** [bsquizz/ocdeployer#37]
ocdeployer deploy -f --sets vmaas --template-dir buildfactory -e builder-env.yml vmaas-qe --secrets-local-dir secrets/sanitized

```
INFO:ocdeployer.deploy:Handling config for service set 'vmaas'

Traceback (most recent call last):

  File "/iqe_venv/bin/ocdeployer", line 8, in <module>

    sys.exit(main())

  File "/iqe_venv/lib64/python3.6/site-packages/click/core.py", line 764, in __call__

    return self.main(*args, **kwargs)

  File "/iqe_venv/lib64/python3.6/site-packages/click/core.py", line 717, in main

    rv = self.invoke(ctx)

  File "/iqe_venv/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/iqe_venv/lib64/python3.6/site-packages/click/core.py", line 956, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/iqe_venv/lib64/python3.6/site-packages/click/core.py", line 555, in invoke

    return callback(*args, **kwargs)

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/__main__.py", line 375, in deploy_to_project

    dry_run=False,

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/deploy.py", line 523, in run

    all_processed_templates[service_set] = self._deploy_service_set(service_set)

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/deploy.py", line 430, in _deploy_service_set

    set_cfg = self._get_service_set_cfg(service_set, dir_path)

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/deploy.py", line 421, in _get_service_set_cfg

    set_env_cfg = self.env_config_handler.get_service_set_env_cfg(dir_path, service_set)

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/env.py", line 190, in get_service_set_env_cfg

    self._get_service_set_vars(service_set_dir, service_set), service_set=service_set

  File "/iqe_venv/lib64/python3.6/site-packages/ocdeployer/env.py", line 139, in _get_service_set_vars

    path = os.path.join(service_set_dir, self.env_dir_name)

AttributeError: 'LegacyEnvConfigHandler' object has no attribute 'env_dir_name'
```

**Comment by bsquizz** [comment]
Thanks I'll take a look. As a work-around for now, put `builder-env` into the `env` dir and run with `-e builder-env`

**Comment by psegedy** [comment]
Thanks for workaround, I fixed the issue, but a few more tests failed due to my fix :smile:, so instead of PR I rather created this issue.
