### ISSUE TITLE
v1.0.4 is missing requirements when installed from Pypi

### ISSUE THREAD

**Issue by tumido** [bsquizz/ocdeployer#6]
Hi @bsquizz! :slightly_smiling_face:

When I install `ocdeployer` via pip, I'm missing some of the dependencies.

```bash
$ pip install ocdeployer
Collecting ocdeployer
  Downloading https://files.pythonhosted.org/packages/ed/28/148a8ae85d97536bd706843a1118585c2d9a057323b5341e92b4b039422b/ocdeployer-1.0.4-py3-none-any.whl
Requirement already satisfied: click in /usr/lib/python3.7/site-packages (from ocdeployer) (7.0)
Collecting sh (from ocdeployer)
  Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Collecting prompter (from ocdeployer)
  Downloading https://files.pythonhosted.org/packages/4d/c3/575cc491b9d0df2c56a64d37a04adcd64de7912fdfd758ad5f542c82e73c/prompter-0.3.10-py2.py3-none-any.whl
Requirement already satisfied: pyyaml in /usr/lib/python3.7/site-packages (from ocdeployer) (3.13)
Installing collected packages: sh, prompter, ocdeployer
Successfully installed ocdeployer-1.0.4 prompter-0.3.10 sh-1.12.14

$ ocdeployer --help                                                                                                                                                                           
Traceback (most recent call last):
  File "/home/tcoufal/.local/bin/ocdeployer", line 6, in <module>
    from ocdeployer.__main__ import main
  File "/home/tcoufal/.local/lib/python3.7/site-packages/ocdeployer/__main__.py", line 14, in <module>
    from ocdeployer.utils import oc, load_cfg_file, get_routes, switch_to_project
  File "/home/tcoufal/.local/lib/python3.7/site-packages/ocdeployer/utils.py", line 14, in <module>
    from wait_for import wait_for, TimedOutError
ModuleNotFoundError: No module named 'wait_for'

$ pip show ocdeployer
Name: ocdeployer
Version: 1.0.4
Summary: A tool which wraps the OpenShift command line tools to enable repeatable automated deployment of OpenShift templates
Home-page: https://www.github.com/bsquizz/ocdeployer
Author: Brandon Squizzato
Author-email: bsquizza@redhat.com
License: MIT
Location: /home/tcoufal/.local/lib/python3.7/site-packages
Requires: click, prompter, sh, pyyaml
Required-by:
```

See the *Requires* line at the end. It seems you've forgot to release new version when you've updated the requirements. [v1.0.4](https://github.com/bsquizz/ocdeployer/tree/1.0.4) is using `wait_for`, yet the dependency is not listed in its `setup.py`.

**Comment by bsquizz** [comment]
Hmm thanks, this is in master but not in the tag, I'll fix soon...

**Comment by tumido** [comment]
I thought you're on vacation! Don't bother with this now, it can wait! :sunglasses:

**Comment by bsquizz** [comment]
Today I'm back :)

**Comment by bsquizz** [comment]
This was fixed
